const { readdirSync, writeFileSync } = require("fs");
const { join } = require("path");

const { genPlot } = require("./utils");

async function main() {
  const algosBatchs = readdirSync(join(__dirname, "algos"))
    .filter((f) => f.endsWith(".js"))
    .map((f) => require(join(__dirname, "algos", f)));
  const plots = [];

  for (const algoBatch of algosBatchs) {
    const { name, algos, test, testCases } = algoBatch;
    console.log(`Running ${name}...`);
    for (const algoKey in algos) {
      const timings = {};
      const errorRates = {};
      let errorRate = 0;
      for (const testCase in testCases) {
        const start = Date.now();
        const testResult = test(algos[algoKey], testCase);
        if (testResult === null) {
          // incapable
          break;
        }
        if (!testResult) {
          errorRate++;
        }
        timings[testCase] = Date.now() - start;
        errorRates[testCase] = errorRate;
      }
      const filename = await genPlot(name, algoKey, timings, errorRates);
      plots.push(filename);
    }
  }

  let readmeData = "# Plots generated by `./algos/*.js`\n";
  for (const plot of plots) {
    readmeData += `## ${plot}\n![${plot}](./plots/${plot})\n`;
  }
  writeFileSync(join(__dirname, "README.md"), readmeData);
}

main();
